### ISSUE TITLE
feature: change output format to hash:plain

### ISSUE THREAD

**Issue by roycewilliams** [sensepost/ltmod#1]
Most cracking utilities use hash:plain format.

Among other benefits, since many hashes are a fixed length, this significantly improves readability. It also makes it easier to parse plains with spaces, colons, etc. as part of a commandline workflow.

**Comment by singe** [comment]
Good point, thank you and done.

https://github.com/sensepost/ntcrack/commit/95ddbcd6f5fc84cc6a77fc0c56929dbe58a0386f
